float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorFlat
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector_flat
    name: pgvector-flat
    run_groups:
      L1000-5-200:
        arg_groups: [{lists: 10000, }]
        args: {}
        query_args:
          - [5, {threads: 1}]
          - [5, {threads: 2}]
          - [5, {threads: 4}]
          - [5, {threads: 8}]
          - [5, {threads: 16}]
          - [5, {threads: 32}]
          - [5, {threads: 64}]
          - [5, {threads: 128}]
          - [10, {threads: 1}]
          - [10, {threads: 2}]
          - [10, {threads: 4}]
          - [10, {threads: 8}]
          - [10, {threads: 16}]
          - [10, {threads: 32}]
          - [10, {threads: 64}]
          - [10, {threads: 128}]
          - [20, {threads: 1}]
          - [20, {threads: 2}]
          - [20, {threads: 4}]
          - [20, {threads: 8}]
          - [20, {threads: 16}]
          - [20, {threads: 32}]
          - [20, {threads: 64}]
          - [20, {threads: 128}]
          - [50, {threads: 1}]
          - [50, {threads: 2}]
          - [50, {threads: 4}]
          - [50, {threads: 8}]
          - [50, {threads: 16}]
          - [50, {threads: 32}]
          - [50, {threads: 64}]
          - [50, {threads: 128}]
          - [100, {threads: 1}]
          - [100, {threads: 2}]
          - [100, {threads: 4}]
          - [100, {threads: 8}]
          - [100, {threads: 16}]
          - [100, {threads: 32}]
          - [100, {threads: 64}]
          - [100, {threads: 128}]
          - [200, {threads: 1}]
          - [200, {threads: 2}]
          - [200, {threads: 4}]
          - [200, {threads: 8}]
          - [200, {threads: 16}]
          - [200, {threads: 32}]
          - [200, {threads: 64}]
          - [200, {threads: 128}]
