float:
  any:
  - base_args: ['@metric']
    constructor: YDBVector
    disabled: false
    docker_tag: ann-benchmarks-ydb
    module: ann_benchmarks.algorithms.ydb
    name: ydb
    run_groups:
      C100-l3:
        arg_groups: [{clusters: 100, levels: 3}]
        args: {}
        query_args: [[40, 80]]
      C200-l3:
        arg_groups: [{clusters: 200, levels: 3}]
        args: {}
        query_args: [[80, 120]]
      C400-l3:
        arg_groups: [{clusters: 400, levels: 3}]
        args: {}
        query_args: [[120, 200]]
      C800-l3:
        arg_groups: [{clusters: 800, levels: 3}]
        args: {}
        query_args: [[200, 400]]
