float:
  any:
  - base_args: ['@metric']
    constructor: YDBVector
    disabled: false
    docker_tag: ann-benchmarks-ydb
    module: ann_benchmarks.algorithms.ydb
    name: ydb
    run_groups:
      C50-l3-o3:
        arg_groups: [{clusters: 50, levels: 3, overlap_clusters: 3}]
        args: {}
        query_args: [[3, 5, 10]]
