float:
  any:
  - base_args: ['@metric']
    constructor: YDBVector
    disabled: false
    docker_tag: ann-benchmarks-ydb
    module: ann_benchmarks.algorithms.ydb
    name: ydb
    run_groups:
      C50-l3-30:
        arg_groups: [{clusters: 50, levels: 3}]
        args: {}
        query_args:
          - [30, {threads: 1}]
          - [30, {threads: 2}]
          - [30, {threads: 4}]
          - [30, {threads: 8}]
          - [30, {threads: 16}]
          - [30, {threads: 32}]
          - [30, {threads: 64}]
          - [30, {threads: 128}]
