float:
  any:
  - base_args: ['@metric']
    constructor: YDBVector
    disabled: false
    docker_tag: ann-benchmarks-ydb
    module: ann_benchmarks.algorithms.ydb
    name: ydb
    run_groups:
      C50-l3-o3:
        arg_groups: [{clusters: 50, levels: 3, overlap_clusters: 3, index_count: 1}]
        args: {}
        query_args:
          - [3, {threads: 64}]
          - [3, {threads: 128}]
          - [5, {threads: 64}]
          - [5, {threads: 128}]
          - [7, {threads: 64}]
          - [7, {threads: 128}]
          - [10, {threads: 64}]
          - [10, {threads: 128}]
          - [12, {threads: 64}]
          - [12, {threads: 128}]
          - [15, {threads: 64}]
          - [15, {threads: 128}]
          - [20, {threads: 64}]
          - [20, {threads: 128}]
          - [25, {threads: 64}]
          - [30, {threads: 64}]
          - [35, {threads: 64}]
          - [40, {threads: 64}]
          - [45, {threads: 64}]
          - [3, {threads: 64, read_replicas: 1}]
          - [3, {threads: 128, read_replicas: 1}]
          - [5, {threads: 64, read_replicas: 1}]
          - [5, {threads: 128, read_replicas: 1}]
          - [7, {threads: 64, read_replicas: 1}]
          - [7, {threads: 128, read_replicas: 1}]
          - [10, {threads: 64, read_replicas: 1}]
          - [10, {threads: 128, read_replicas: 1}]
          - [12, {threads: 64, read_replicas: 1}]
          - [12, {threads: 128, read_replicas: 1}]
          - [15, {threads: 64, read_replicas: 1}]
          - [15, {threads: 128, read_replicas: 1}]
          - [20, {threads: 64, read_replicas: 1}]
          - [20, {threads: 128, read_replicas: 1}]
          - [25, {threads: 64, read_replicas: 1}]
          - [25, {threads: 128, read_replicas: 1}]
          - [30, {threads: 64, read_replicas: 1}]
          - [30, {threads: 128, read_replicas: 1}]
          - [35, {threads: 64, read_replicas: 1}]
          - [35, {threads: 128, read_replicas: 1}]
          - [40, {threads: 64, read_replicas: 1}]
          - [40, {threads: 128, read_replicas: 1}]
          - [45, {threads: 64, read_replicas: 1}]
          - [45, {threads: 128, read_replicas: 1}]
          - [80, {threads: 128, read_replicas: 1}]
          - [160, {threads: 64, read_replicas: 1}]
          - [220, {threads: 64, read_replicas: 1}]
          - [240, {threads: 64, read_replicas: 1}]
          - [300, {threads: 64, read_replicas: 1}]
