float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      M-24-400:
        arg_groups: [{M: 24, efConstruction: 200}]
        args: {}
        query_args:
          - [10, {threads: 1}]
          - [10, {threads: 2}]
          - [10, {threads: 4}]
          - [10, {threads: 8}]
          - [10, {threads: 16}]
          - [10, {threads: 32}]
          - [10, {threads: 64}]
          - [10, {threads: 128}]
