float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorHNSW
    disabled: false
    docker_tag: ann-benchmarks-pgvector-hnsw
    module: ann_benchmarks.algorithms.pgvector_hnsw
    name: pgvector_hnsw
    run_groups:
      pgvector_hnsw1:
        args: [
            ["postgres://vec@localhost:5432/vec"],
            [24], # m
            [200], # ef_construction
          ]
        query_args: [[10, 15, 20]] # ef_search
